// <auto-generated />
namespace WpfApp_ogrenciOtomasyonu.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class cinsiyet_char_change_string : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cinsiyet_char_change_string));
        
        string IMigrationMetadata.Id
        {
            get { return "201504141822538_cinsiyet_char_change_string"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
