// <auto-generated />
namespace WpfApp_ogrenciOtomasyonu.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DataAnnotations_sample : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DataAnnotations_sample));
        
        string IMigrationMetadata.Id
        {
            get { return "201504150104234_DataAnnotations_sample"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
