// <auto-generated />
namespace WpfApp_ogrenciOtomasyonu.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class sinif_eklendi_data_annotations_eklendi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sinif_eklendi_data_annotations_eklendi));
        
        string IMigrationMetadata.Id
        {
            get { return "201504150401244_sinif_eklendi_data_annotations_eklendi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
