// <auto-generated />
namespace WpfApp_ogrenciOtomasyonu.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class son : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(son));
        
        string IMigrationMetadata.Id
        {
            get { return "201504150719457_son"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
